[package]
name = "rigid_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_mod_picking = "0.20.1"

[profile.dev]
opt-level = 1 # Use slightly better optimization, so examples work

[[example]]
name = "rigid_sim_demo"
path = "examples/rigid_sim_demo.rs"
